apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: stage
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      serviceAccountName: guestbook-sa
      containers:
      - image: docker.io/fdaluisio/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
